### ISSUE TITLE
Design Istanbul Conference Logo

### ISSUE THREAD

**Issue by iggysiggy** [oxfordglobal/things-to-do#13]
I'm splitting this off from #6 to keep things separate.  We want a tentative logo for the conference to show the Istanbul team.  They suggested incorporating the silhouette of the Istanbul skyline.

**Comment by iggysiggy** [comment]
Here are two options: one with waves, and one without waves.  I can't decide which I prefer.  The styling of the water can be adjusted (smoother waves, shorter waves, fewer waves, etc.), and the color can be changed.  I envision the name of the conference extending from the right of the logo. @esoli 
![globalmun istanbul-water](https://cloud.githubusercontent.com/assets/10913411/6795833/1e6f76e0-d1bd-11e4-8399-f40481acd1f7.jpg)
![globalmun istanbul-no water](https://cloud.githubusercontent.com/assets/10913411/6795834/1e6fdf54-d1bd-11e4-9c5f-949a6cfa6c85.jpg)

**Comment by esoli** [comment]
These look really nice! I think I prefer the version without the waves, but then it's harder to tell what that floating boat is. So actually maybe we'll want the waves in the end.

I also just thought of something else. Since this conference logo will clearly be very Turkey-specific, how should we go about building up our own brand. Perhaps we can just show our OGED logo alongside this every time? Or should we try to incorporate an element of our own logo into every other conference logo (assuming we organise more than one over the course of our existence).

**Comment by gyodt** [comment]
Looks great! I like the one without waves. Maybe a move obvious/traditional boat silhouette would work better? Like a sailboat?

Interesting idea Erfan about possibly having common elements in all our conference logos. Not sure yet what to think about it.

**Comment by iggysiggy** [comment]
To address both those points:
-The boat is actually not a boat, it's a [famous tower](http://en.wikipedia.org/wiki/Maiden%27s_Tower) in the Bosphorus.  It's one of the iconic elements of the Istanbul skyline, and will be immediately recognizable to any Istanbullu, which is really our main audience for the details of the logo.
-I kind of like what [Thimun](http://www.thimun.org/) does with their logos--they have unique logos for each conference that somehow relate to the conference location, but there is a clear common thread among them.  My thinking for this is that we would do something similar, but less structured: the olive branches around some circular element that is specific to where the conference is being held.  Textual elements accompanying the graphic can also carry over styling.  Then, we can more subtly include the Oxford Global logo at the bottom of any materials we produce.

**Comment by gyodt** [comment]
WOOOOO!!
