### ISSUE TITLE
Current version of Vesting Agreement

### ISSUE THREAD

**Issue by esoli** [oxfordglobal/things-to-do#9]
Each share has full rights in the company with respect to voting, dividends and distributions. Redemption of shares shall be carried out only by agreement of a majority of shareholders. There shall be a VESTING PERIOD of 1460 days. Redeemable Shares shall convert to Ordinary Shares according to the following formula:

1. In the first year of the VESTING PERIOD, all shares remain redeemable.
2. After the full VESTING PERIOD, all shares shall be converted to Ordinary Shares.
3. In the second, third, and fourth years of the VESTING PERIOD, the number of shares redeemable shall be calculated according to the ratio of 'days remaining in the VESTING PERIOD' to 'the total VESTING PERIOD' ('days remaining in VESTING PERIOD' / '1460 days' x 'shareholder's total shares').
4. The redemption price shall be the same as the issue price.

**Comment by esoli** [comment]
FYI, the issue price mentioned in part 4 is £0.01, and there are 100 shares initially declared (for a total of £1)

**Comment by iggysiggy** [comment]
This looks good to me.  I'll reference it against some other agreements this weekend to see if there's anything worth adding.

**Comment by iggysiggy** [comment]
I have a few points worth considering:
-Should we need to do something to exercise our options, or should it be automatic after 4 years?
-Should the company have a right of repurchase (i.e., if the majority of shareholders agree to redeem shares, does that automatically happen, or can the shareholder refuse?).  I think there should be a right of repurchase, as otherwise, one of us could quit now and just hang out for four years, and the full shares would vest anyway.  This would mean that three of us could theoretically band together to kick out the fourth, but I can't think of a good way around this.
-Should we place any restrictions on sale or transfer of shares?  I suggest that redeemable shares should not be able to be transferred or sold.
-If the company does redeem shares, to whom do they go?  I suggest that they be divided equally among whoever of the four of us remains, but if we are to do that, we need to decide how to define that in writing--saying that the redeemed shares will be divided equally among shareholders or directors does not necessarily work, because we may eventually add more of each.
-If we decide to offer equity to another person, where should those shares come from?  Should we consider an agreement to never offer anyone else equity as compensation?
